name: Publish
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  call-dotnet-publish-workflow:
    uses: devantler-tech/.github/.github/workflows/dotnet-publish.yaml@main
    secrets: inherit
