name: Readme Tree

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  call-readme-tree-workflow:
    uses: devantler-tech/.github/.github/workflows/readme-tree.yaml@main
    secrets: inherit
