name: Readme Tree

on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tree:
    runs-on: ubuntu-latest
    name: readme-tree
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Create README Tree
        uses: RavelloH/readme-tree@v1.1.0
        with:
          showdirectoryname: "yes"
      - name: Commit README tree changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Commit README tree changes
