name: Test

on:
  pull_request:
    # Added 'edited' temporarily, as there currently is no trigger for when the base branch is updated.
    # https://github.com/orgs/community/discussions/64119
    types: [opened, synchronize, reopened, ready_for_review, closed, edited]
    branches: main
  push:
    branches: main
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    if: github.event.pull_request.draft == false
    steps:
      - name: 📑 Checkout
        uses: actions/checkout@v4
      - name: ⚙️ Setup .NET
        uses: actions/setup-dotnet@v4
      - name: 🧪 Test
        run: dotnet test --collect:"XPlat Code Coverage"
      - name: 📄 Upload Code Coverage to CodeCov
        uses: codecov/codecov-action@v4
        with:
          files: ./*.Tests/TestResults/**/coverage.cobertura.xml
          fail_ci_if_error: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
